name: Checks
on:
  pull_request:
    types: [opened, synchronize] # PR is opened or modified
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Checkout all branches and tags
    - name: "Use NodeJS 16" # Setup node using version 16
      uses: actions/setup-node@v2 # Public action
      with: 
        node-version: '16'
    - name: "Setup npm"
      run: |
        npm set @brandon_selfbook:registry=https://registry.npmjs.org/brandon_selfbook
        npm set "//registry.npmjs.org/:_authToken=${{ secrets.GITHUB_TOKEN }}"
    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile
    - name: Run tests
      run: yarn lerna exec yarn test