name: Publish
on:
  pull_request:
    types: [closed]
    branches:
      - development
      - main
jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: "Use NodeJS 16"
      uses: actions/setup-node@v2
      with: 
        node-version: '16'
        registry-url: 'https://registry.npmjs.org'
    # - name: "Setup npm"
    #   run: |
    #     npm set @brandon_selfbook:registry=https://registry.npmjs.org/brandon_selfbook
    #     npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"
    - name: "Version and publish"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"

        if [ ${{ github.base_ref }} = development ]; then
          yarn lerna version --conventional-commits --conventional-prerelease --preid beta --yes
        else
          yarn lerna version --conventional-commits --conventional-graduate --yes
        fi

        yarn lerna publish from-git --yes
